import React, { useState, useEffect } from 'react';
import { RotateCcw, FileDown, Clock, Pause, Play, Shuffle, Printer, X } from 'lucide-react';
import { Button } from '../ui/Button';
import { Modal } from '../ui/Modal';
import { useMemoryGame } from './useMemoryGame';

import MemoryBoard from './MemoryBoard';
import MemoryPrintPreview from './MemoryPrintPreview';
import MemoryConfigModal from './MemoryConfigModal';
import MemoryVictoryModal from './MemoryVictoryModal';

import { useActivity } from '../../contexts/ActivityContext';
import { useGemini } from '../../contexts/GeminiContext';
import { toDirectImageUrl, handleDriveImageError } from '../../utils/urlUtils';

const MemoryGame = ({ isFullWidth }) => {

    const { geminiService, selectedModel } = useGemini();
    const { activeActivity, updateActivityData } = useActivity();

    // Config Modal State
    const [showConfigModal, setShowConfigModal] = useState(false);
    const [showPrintPreview, setShowPrintPreview] = useState(false);
    const [showVictoryModal, setShowVictoryModal] = useState(false);
    const [expandedCard, setExpandedCard] = useState(null);

    const [gameMode, setGameMode] = useState(activeActivity?.data?.gameMode || 'ai');
    const [manualPairs, setManualPairs] = useState(activeActivity?.data?.manualPairs || []);
    const [cardBackQuestion, setCardBackQuestion] = useState(activeActivity?.data?.cardBackQuestion || null);
    const [cardBackAnswer, setCardBackAnswer] = useState(activeActivity?.data?.cardBackAnswer || null);

    const {
        gameState, setGameState,
        topic, setTopic,
        cards,
        flipped, solved, moves, time,
        isPaused, setIsPaused,
        bgImage, setBgImage,
        cardBackImage, setCardBackImage,
        useCardImages,
        startGameFromBuilder, // We will use this to init game from Modal
        resetGame,
        getCardsForPrint,
        handleCardClick,
        shuffleCurrentGame
    } = useMemoryGame(geminiService, activeActivity?.data, selectedModel);

    // Auto-open modal if new activity or reset
    useEffect(() => {
        if (gameState === 'input' && !showConfigModal) {
            setShowConfigModal(true);
        }
    }, [gameState]);

    // Show Victory Modal when game is won
    useEffect(() => {
        if (gameState === 'won') {
            setShowVictoryModal(true);
        } else {
            setShowVictoryModal(false);
        }
    }, [gameState]);

    // Save State
    useEffect(() => {
        if (activeActivity && gameState !== 'input') {
            const dataToSave = {
                gameState, topic, cards, solved, moves, bgImage, cardBackImage, useCardImages,
                gameMode, manualPairs
            };
            updateActivityData(activeActivity.id, { data: dataToSave });
        }
    }, [gameState, topic, cards, solved, moves, bgImage, cardBackImage, useCardImages, gameMode, manualPairs, activeActivity?.id]);


    const handleConfigConfirm = (configData) => {
        setTopic(configData.topic);

        // Update separate card back images with fallback
        if (configData.cardBackQuestion !== undefined) setCardBackQuestion(configData.cardBackQuestion);
        if (configData.cardBackAnswer !== undefined) setCardBackAnswer(configData.cardBackAnswer);
        // Legacy single image (used when editing saved games that had cardBackImage)
        if (configData.cardBackImage) {
            setCardBackImage(configData.cardBackImage);
        }

        if (configData.type === 'ai') {
            // Cards already generated by Service in Modal
            startGameFromBuilder(configData.topic, configData.cards);
        } else if (configData.type === 'manual') {
            // Transform pairs to cards
            const newCards = [];
            configData.pairs.forEach((p, i) => {
                newCards.push({
                    id: `p${i}-a`,
                    pairId: i,
                    content: p.text1 || '',
                    type: 'question',
                    customImage: p.image1
                });
                newCards.push({
                    id: `p${i}-b`,
                    pairId: i,
                    content: p.text2 || '',
                    type: 'answer',
                    customImage: p.image2
                });
            });
            // Shuffle happens in useMemoryGame? No, startGameFromBuilder expects pairs or cards?
            // Actually startGameFromBuilder in useMemoryGame shuffles.
            // Wait, previous UseMemoryGame expects "customPairs" (array of simple objects) OR ...
            // Let's assume we pass cards directly. 
            // I'll check usage: `startGameFromBuilder(text, pairs)` -> `generateCardsFromPairs`.
            // I'll stick to passing "cards" array (already formatted) if I modify `useMemoryGame` slightly or use `startGameFromBuilder` carefully.

            // Actually, best to just pass formatted cards to a "initGame" function. 
            // Since `startGameFromBuilder` takes (topic, pairList), I'll repurpose it or add `startNewGame(topic, cards)`.
            // For now I'll pass keys that `startGameFromBuilder` might not expect if I don't check `useMemoryGame`.
            // Let's look at `useMemoryGame` later. For now, I'll pass the cards.

            startGameFromBuilder(configData.topic, newCards);
        }
        setShowConfigModal(false);
    };

    // Format time for display
    const formatTime = (seconds) => {
        const mins = Math.floor(seconds / 60);
        const secs = seconds % 60;
        return `${mins}:${secs.toString().padStart(2, '0')}`;
    };

    return (
        <div className="h-full min-h-[600px] bg-brown-50 text-brown-900 flex flex-col relative font-sans rounded-none lg:rounded-b-2xl">
            {/* Header */}
            <header className="p-4 border-b border-brown-100 flex items-center justify-between bg-brown-50/50 rounded-t-2xl sticky top-0 z-10 backdrop-blur-md">
                <div className="flex items-center gap-3">
                    <div className="flex items-center gap-2">
                        <div className={`w-2 h-2 rounded-full ${gameState === 'playing' ? (isPaused ? 'bg-yellow-500' : 'bg-green-500') : 'bg-brown-300'}`}></div>
                        <h1 className="font-bold text-lg text-brown-800 uppercase text-xs sm:text-sm tracking-wide">
                            {topic || "Jogo da Memória"}
                        </h1>
                    </div>
                    {/* Timer & Moves Display */}
                    {(gameState === 'playing' || gameState === 'won') && (
                        <div className="flex items-center gap-3 ml-4 text-sm font-medium text-brown-600 bg-brown-100/50 px-3 py-1 rounded-full">
                            <div className="flex items-center gap-1">
                                <Clock size={14} />
                                <span>{formatTime(time)}</span>
                            </div>
                            <div className="w-px h-3 bg-brown-300"></div>
                            <div>
                                {moves} jogadas
                            </div>
                            <div className="w-px h-3 bg-brown-300"></div>
                            <button
                                onClick={() => setIsPaused(!isPaused)}
                                className={`p-1 rounded-full hover:bg-brown-200 transition-colors ${isPaused ? 'text-yellow-600 bg-yellow-100' : 'text-brown-600'}`}
                                title={isPaused ? "Continuar" : "Pausar"}
                            >
                                {isPaused ? <Play size={14} fill="currentColor" /> : <Pause size={14} fill="currentColor" />}
                            </button>
                        </div>
                    )}
                    <div className="flex gap-1 mr-2 border-r border-brown-200 pr-2">
                        {(gameState === 'playing' || gameState === 'won') && (
                            <>
                                <Button variant="secondary" onClick={shuffleCurrentGame} className="h-9 w-9 p-0" title="Embaralhar Cartas">
                                    <Shuffle className="w-5 h-5" />
                                </Button>
                                <Button variant="secondary" onClick={() => {
                                    if (window.confirm('Quer reiniciar este jogo?')) shuffleCurrentGame();
                                }} className="h-9 w-9 p-0" title="Reiniciar Jogo">
                                    <RotateCcw className="w-5 h-5" />
                                </Button>
                            </>
                        )}
                    </div>
                </div>
                <div className="flex gap-2">
                    <Button variant="primary" onClick={() => setShowConfigModal(true)} className="h-9 px-4 text-sm">
                        <RotateCcw className="w-4 h-4 mr-2" />
                        {gameState === 'playing' || gameState === 'won' ? "Editar" : "Configurar"}
                    </Button>
                    <Button variant="ghost" onClick={() => setShowPrintPreview(true)} className="h-9 w-9 p-0" title="Imprimir">
                        <Printer className="w-5 h-5" />
                    </Button>
                </div>
            </header>

            {/* Main Content */}
            <main className={`flex-1 p-2 sm:p-4 overflow-y-auto relative z-10 w-full ${isFullWidth ? '' : 'max-w-7xl mx-auto'} custom-scrollbar flex flex-col`}>

                {/* Empty State (Waiting for Config) */}
                {gameState === 'input' && (
                    <div className="flex-1 flex flex-col items-center justify-center text-brown-300 select-none">
                        <p>Aguardando configuração...</p>
                    </div>
                )}

                {/* Loading State */}
                {gameState === 'loading' && (
                    <div className="flex-1 flex flex-col items-center justify-center space-y-4">
                        <div className="w-12 h-12 border-4 border-brown-200 border-t-brown-600 rounded-full animate-spin"></div>
                        <p className="text-brown-600 font-medium animate-pulse">Gerando cartas com IA...</p>
                    </div>
                )}

                {/* Game Board */}
                {(gameState === 'playing' || gameState === 'won') && (
                    <div className="relative">
                        <MemoryBoard
                            cards={cards}
                            flipped={flipped}
                            solved={solved}
                            handleCardClick={handleCardClick}
                            onExpand={(card) => setExpandedCard(card)}
                            cardBackQuestion={cardBackQuestion}
                            cardBackAnswer={cardBackAnswer}
                            cardBackImage={cardBackImage}
                            useCardImages={useCardImages}
                            isFullWidth={isFullWidth}
                        />
                        {/* Paused Overlay */}
                        {isPaused && (
                            <div className="absolute inset-0 bg-brown-50/80 backdrop-blur-sm z-50 flex flex-col items-center justify-center rounded-xl animate-in fade-in">
                                <div className="bg-white p-8 rounded-2xl shadow-xl text-center space-y-4 border border-brown-100 transform scale-110">
                                    <div className="w-16 h-16 bg-yellow-100 rounded-full flex items-center justify-center mx-auto text-yellow-600 mb-2">
                                        <Pause size={32} />
                                    </div>
                                    <h2 className="text-2xl font-bold text-brown-800">Jogo Pausado</h2>
                                    <p className="text-brown-600">O tempo está parado. Respire fundo!</p>
                                    <Button onClick={() => setIsPaused(false)} className="w-full text-lg h-12 mt-2">
                                        <Play size={20} className="mr-2" /> Continuar Jogo
                                    </Button>
                                </div>
                            </div>
                        )}
                    </div>
                )}

                {/* Expanded Card Overlay */}
                {expandedCard && (
                    <div 
                        className="fixed inset-0 z-[100] flex items-center justify-center bg-black/80 backdrop-blur-sm p-4 sm:p-8 animate-in fade-in"
                        onClick={() => setExpandedCard(null)}
                    >
                        <div 
                            className="relative bg-gradient-to-br from-brown-700 to-brown-950 rounded-2xl w-full max-w-4xl aspect-[3/4] sm:aspect-auto sm:h-[85vh] flex flex-col items-center justify-center overflow-hidden shadow-2xl ring-4 ring-white/20"
                            onClick={(e) => e.stopPropagation()}
                        >
                            <button 
                                onClick={() => setExpandedCard(null)}
                                className="absolute top-4 right-4 z-50 p-2 bg-black/30 hover:bg-black/60 text-white rounded-full transition-colors"
                            >
                                <X size={28} />
                            </button>
                            
                            {useCardImages && expandedCard.customImage && (
                                <div className="absolute inset-0 z-0">
                                    <img src={toDirectImageUrl(expandedCard.customImage)} alt="" className="w-full h-full object-contain" referrerPolicy="no-referrer" onError={handleDriveImageError} />
                                </div>
                            )}
                            
                            <div className={`relative z-10 p-6 sm:p-12 flex flex-col items-center w-full h-full ${useCardImages && expandedCard.customImage ? 'justify-end pb-12' : 'justify-center'}`}>
                                <span className={`font-bold text-center leading-relaxed text-white
                                    ${useCardImages && expandedCard.customImage ? 'bg-black/50 px-6 py-4 rounded-2xl backdrop-blur-sm shadow-xl' : 'drop-shadow-md'}
                                    text-3xl sm:text-5xl md:text-6xl`}
                                >
                                    {expandedCard.content}
                                </span>
                            </div>
                        </div>
                    </div>
                )}
            </main>

            {/* Modals */}
            <MemoryConfigModal
                isOpen={showConfigModal}
                onClose={() => setShowConfigModal(false)}
                onConfirm={(data) => {
                    // Logic to start game based on data type
                    let cardsToPlay = data.cards;

                    setGameMode(data.type);
                    if (data.type === 'manual' && data.pairs) {
                        setManualPairs(data.pairs);
                        cardsToPlay = [];
                        data.pairs.forEach(p => {
                            cardsToPlay.push({ id: p.id + '_1', pairId: p.id, type: 'text', content: p.text1, customImage: p.image1 });
                            cardsToPlay.push({ id: p.id + '_2', pairId: p.id, type: 'text', content: p.text2, customImage: p.image2 });
                        });
                    }

                    startGameFromBuilder(data.topic, cardsToPlay);

                    // Always update back image (if provided or explicitly nullified in modal)
                    // If undefined, maybe keep current? But Modal sends it.
                    if (data.cardBackImage !== undefined) {
                        setCardBackImage(data.cardBackImage);
                    }

                    setShowConfigModal(false);
                }}
                initialData={{
                    gameState,
                    topic: topic || activeActivity?.data?.topic,
                    lessonDetails: activeActivity?.data?.lessonDetails,
                    cards,
                    cardBackImage,
                    gameMode,
                    manualPairs
                }}
            />

            {showPrintPreview && (
                <MemoryPrintPreview
                    items={getCardsForPrint()}
                    cardBackImage={cardBackImage}
                    topic={topic}
                    onClose={() => setShowPrintPreview(false)}
                />
            )}

            <MemoryVictoryModal
                isOpen={showVictoryModal}
                onClose={() => setShowVictoryModal(false)}
                moves={moves}
                time={time}
                topic={topic}
                onRestart={() => {
                    if (window.confirm('Jogar novamente com as mesmas cartas? (Cancele para configurar novo jogo)')) {
                        shuffleCurrentGame();
                    } else {
                        setShowConfigModal(true);
                    }
                }}
            />
        </div>
    );
};

export default MemoryGame;
